name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Hugging Face Spaces
        env:
          ICT_TOKEN: ${{ secrets.ICT_TOKEN }}
        run: |
          git config --global user.email "asif.arif@gmail.com"
          git config --global user.name "asifarif"
          git remote add space https://huggingface.co/spaces/muasif/ict-exam-prep
          git push --force https://muasif:${ICT_TOKEN}@huggingface.co/spaces/muasif/ict-exam-prep main
